#!/usr/bin/env bash

notify() {
    in=`cat`
    if [ "$in" == "" ]; then return; fi
    while read line; do
        tmux -S "$TMUX_SOCKET" display-message "$1: $line"
        if build central enabled; then
            build central notify "${1}" "${line}"
        else
            if build system is-mac; then
                echo "$line" | mac_notify "$1"
            else
                [ "$DISPLAY" ] || export DISPLAY=$(who -u | awk '/\s:[0-9]\s/ {print $2}')
                notify-send -t 50 "$1" "$line"
            fi
            sleep 1;
        fi
    done < <(echo "$in")
}

mac_notify() {
    build etc timeout 3 osascript -e "display notification \"`echo "$line" | sed 's/\"//g'`\" with title \"$1\""
}


a="$1"
shift

if [ "$a" == "notify" ]; then
    notify "$@"
elif [ "$a" == "" ]; then
    notify "$@"
else
    echo "notify: help"
fi
