#!/usr/bin/env bash

offline() {
    echo -e "GET http://google.com HTTP/1.0\n\n" | do-timeout 5 nc google.com 80 > /dev/null 2>&1
    if [[ $? -eq 0 ]]; then
            echo "Online"
    fi
}

exists() {
    command -v $@ >/dev/null 2>&1
}

do-timeout() {
    if exists timeout; then
        timeout "$@"
    elif exists gtimeout; then
        gtimeout "$@"
    elif exits /usr/local/bin/gtimeout; then
        /usr/local/bin/gtimeout "$@"
    else
        echo "No Timeout Commands Available"
    fi
}

os() {
    if [ "$(uname)" == "Darwin" ]; then
        echo "Mac"
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        echo "Linux"
    elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
        echo "Windows"
    fi
}

is_mac() {
    [ "$(uname -s)" == "Darwin" ] && exit 0 || exit 1
}

# Credit: http://nparikh.org/notes/zshrc.txt
extract() {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2)  tar -jxvf "$1"                        ;;
      *.tar.gz)   tar -zxvf "$1"                        ;;
      *.bz2)      bunzip2 "$1"                          ;;
      *.dmg)      hdiutil mount "$1"                    ;;
      *.gz)       gunzip "$1"                           ;;
      *.tar)      tar -xvf "$1"                         ;;
      *.tbz2)     tar -jxvf "$1"                        ;;
      *.tgz)      tar -zxvf "$1"                        ;;
      *.zip)      unzip "$1"                            ;;
      *.ZIP)      unzip "$1"                            ;;
      *.pax)      cat "$1" | pax -r                     ;;
      *.pax.Z)    uncompress "$1" --stdout | pax -r     ;;
      *.Z)        uncompress "$1"                       ;;
      *) echo "'$1' cannot be extracted/mounted via extract()" ;;
    esac
  else
     echo "'$1' is not a valid file to extract"
  fi
}

a="$1"
shift

if [ "$a" == "online" ]; then
    offline $@
elif [ "$a" == "timeout" ]; then
    do-timeout "$@"
elif [ "$a" == "exists" ]; then
    exists "$@"
elif [ "$a" == "extract" ]; then
    extracts "$@"
elif [ "$a" == "is-mac" ]; then
    is_mac "$@"
else
    echo "online: echos online if can reach google.com"
    echo "timeout: finds the appropriate timeout command and runs it"
    echo "exists: exits as bool if command exists"
    echo "extract: unzip anything"
fi
