#!/usr/bin/env bash

etc::timeout() {
    if build system exists timeout; then
        timeout "$@"
    elif build system exists gtimeout; then
        gtimeout "$@"
    elif build system exits /usr/local/bin/gtimeout; then
        /usr/local/bin/gtimeout "$@"
    else
        echo "No Timeout Commands Available"
    fi
}

# Credit: http://nparikh.org/notes/zshrc.txt
etc::extract() {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2)  tar -jxvf "$1"                        ;;
      *.tar.gz)   tar -zxvf "$1"                        ;;
      *.bz2)      bunzip2 "$1"                          ;;
      *.dmg)      hdiutil mount "$1"                    ;;
      *.gz)       gunzip "$1"                           ;;
      *.tar)      tar -xvf "$1"                         ;;
      *.tbz2)     tar -jxvf "$1"                        ;;
      *.tgz)      tar -zxvf "$1"                        ;;
      *.zip)      unzip "$1"                            ;;
      *.ZIP)      unzip "$1"                            ;;
      *.pax)      cat "$1" | pax -r                     ;;
      *.pax.Z)    uncompress "$1" --stdout | pax -r     ;;
      *.Z)        uncompress "$1"                       ;;
      *) echo "'$1' cannot be extracted/mounted via extract()" ;;
    esac
  else
     echo "'$1' is not a valid file to extract"
  fi
}

a="$1"
shift

if [ "$a" == "timeout" ]; then
    etc::timeout "$@"
elif [ "$a" == "extract" ]; then
    etc::extract "$@"
else
    echo "timeout: finds the appropriate timeout command and runs it"
    echo "extract: unzip anything"
fi
