#!/usr/bin/env python3
from flask import Flask, request
from flask_socketio import SocketIO

app = Flask(__name__,  static_url_path='/static')
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route("/")
def hello():
    return """
<script type="text/javascript" src="static/socketio.min.js"></script>
<script type="text/javascript" charset="utf-8">
    document.title="Central"
    var socket = io.connect('http://' + document.domain + ':' + location.port);
    socket.on('connect', function() {
        socket.emit('my event', {data: 'I\\'m connected!'});
    });
    socket.on('open url', function(data) {
        console.log(data)
        window.open(data["url"], target="_blank")
    });

    Notification.requestPermission(function (permission) {});
    function notify(title, message) {
        var notification = new Notification(title, {body: message});
    }
    socket.on('notify', function(data) {
    notify(data["title"], data["message"])
    });
</script>
    """

@app.route("/notify", methods=["POST"])
def notify():
    title = request.form["title"]
    message = request.form["message"]
    socketio.emit('notify', {"title": title, "message":message})
    return ""

@app.route("/open/url", methods=["POST"])
def open_url():
    url = request.form["url"]
    socketio.emit('open url', {"url": url})
    return ""

@socketio.on('my event')
def handle_message(message):
    pass

if __name__ == "__main__":
    socketio.run(app, port=8008)
