#!/usr/bin/env bash

list-python() {
    python$1 -m pipdeptree -f -w silence 2>/dev/null | grep -v '^ ' | sort || pip$1 freeze
}

list-python3() { list-python 3; }

leftover() {
    # grep -v -x -F "$2" "$1"
    # sort "$1" "$2" |uniq -u
    comm -2 -3 <(sort "$2") <(sort "$1")
}

uninstall-generic() {
    lister="$1"
    uninstaller="$2"

    old="empty"
    left="$3"
    while [ "$old" != "$new" ]; do
        old="`$lister`"
        while read -r i; do
            [ "$i" != "" ] && $uninstaller "$i"
        done <<< "$left"
        new="`$lister`"
        left="`leftover <(echo "$old") <(echo "$new")`"
    done
}

uninstall-pip3() {
    uninstall-generic "list-python3" "pip3 uninstall -y" "$@"
}

uninstall-pip() {
    uninstall-generic "list-python" "pip uninstall -y" "$@"
}

uninstall-brew() {
    uninstall-generic "brew leaves" "brew uninstall" "$@"
}

uninstall-cask() {
    brew cask uninstall "$@"
}

a="$1"
shift

if [ "$a" == "pip" ]; then
    uninstall-pip "$@"
elif [ "$a" == "pip3" ]; then
    uninstall-pip3 "$@"
elif [ "$a" == "brew" ]; then
    uninstall-brew "$@"
elif [ "$a" == "cask" ]; then
    uninstall-cask "$@"
else
    echo "uninstall recursively (all unique dependecies)"
    echo "pip, pip3, brew, cask"
fi
