#!/usr/bin/env bash

list-python() {
  (python$1 -m pipdeptree -f -w silence 2>/dev/null | grep -v '^ ' | sort || pip$1 freeze) | awk -F'==' '{print $1}'
}

list-python3() { list-python 3; }

leftover() {
    # grep -v -x -F "$2" "$1"
    # sort "$1" "$2" |uniq -u
    comm -2 -3 <(sort "$2") <(sort "$1")
}

uninstall-generic() {
    if [ "$3" == "-f" ]; then
        uninstall-file "$1" "$2" "$4"
        return
    fi
    lister="$1"
    uninstaller="$2"

    old="empty"
    left="$3"
    while [ "$old" != "$new" ]; do
        old="`$lister`"

        echo "Removing:"
        echo "$left"
        read -p "continue[y/N] " c
        [ "$c" != "y" ] && return

        while read -r i; do
            [ "$i" != "" ] && $uninstaller "$i"
        done <<< "$left"
        new="`$lister`"
        left="`leftover <(echo "$old") <(echo "$new")`"
    done
}

uninstall-file() {
  lister="$1"
  uninstaller="$2"
  file="$3"
  [ ! -f "$file" ] && echo "file must exist" &&  return 1
  correct=$(cat "$file")
  while [ "$correct" != "$($lister)" ]; do
      remove=$(leftover $file <($lister))
      echo "Remove:"
      echo $remove
      read -p "continue[y/N] " c
      [ "$c" != "y" ] && return
      while read -r i; do
          [ "$i" != "" ] && $uninstaller "$i"
      done <<< "$remove"
  done
}

uninstall-pip3() {
    uninstall-generic "list-python3" "pip3 uninstall -y" "$@"
}

uninstall-pip2() {
    uninstall-generic "list-python" "pip2 uninstall -y" "$@"
}

uninstall-brew() {
    uninstall-generic "brew leaves" "brew uninstall" "$@"
}

uninstall-cask() {
    brew cask uninstall "$@"
}

a="$1"
shift

if [ "$a" == "pip2" ]; then
    uninstall-pip2 "$@"
elif [ "$a" == "pip3" ]; then
    uninstall-pip3 "$@"
elif [ "$a" == "brew" ]; then
    uninstall-brew "$@"
elif [ "$a" == "cask" ]; then
    uninstall-cask "$@"
else
    echo "pip2: uninstall recursively (all unique dependecies)"
    echo "pip3: uninstall recursively (all unique dependecies)"
    echo "brew: uninstall recursively (all unique dependecies)"
    echo "cask: uninstall recursively (all unique dependecies)"
fi
