#!/usr/bin/env bash

scriptdir=$(cd $(dirname $([ -L "$0" ] && readlink "$0" || echo "$0")) && pwd)

ios::create-icon() {
  if [ -f "icon.svg" ]; then
      echo "icon.svg already exists"
      return 1
  fi
  cp "$scriptdir/icon.svg" icon.svg
}

ios::generate-icons() {
  path=""
  icon=""
  [ -f "${icon}" ] || icon="icon.svg"
  [ -d "${path}" ] || path="."
  base="$(cd "${path}" || exit; basename *.xcodeproj)"
  proj_path="${base%.*}"
  if [ ! -d "${proj_path}" ]; then
      echo "could not find project path: ${proj_path}"
      echo "run this from the same directory as the xcodeproj and icon.svg files."
      return 1
  fi

  image_path="${proj_path}/Assets.xcassets/AppIcon.appiconset"
  if [ ! -d "${image_path}" ]; then
      echo "cannot find icon asset path: ${image_path}"
      return 1
  fi
  ios::generate-icons-internal "${image_path}" "${icon}" && ios::generate-contents "${image_path}"

}

ios::generate-contents() {
  path="$1"
  if [ ! -d "${path}" ]; then
      echo "not a real path: ${path}"
      return 1
  fi
  cp "${scriptdir}"/Contents.json "${path}"
}

ios::generate-icons-internal() {
  path="$1"
  icon="$2"
  if [ ! -d "${path}" ]; then
      echo "not a real path: ${path}"
      return 1
  fi
  if [ ! -f "${icon}" ]; then
      echo "not a real icon: ${icon}"
      echo "create an icon with: ios create-icon"
  fi
  while read line; do
      # shellcheck disable
      inkscape -D -z "${icon}" --export-id=icon -j -o "${path}/"${line} || return 1
  done <<EOF
Icon.png -h 1024 -w 1024
icon_20pt.png -h 20 -w 20
icon_20pt@2x-1.png -h 40 -w 40
icon_20pt@2x.png -h 40 -w 40
icon_20pt@3x.png -h 60 -w 60
icon_29pt.png -h 29 -w 29
icon_29pt@2x-1.png -h 58 -w 58
icon_29pt@2x.png -h 58 -w 58
icon_29pt@3x.png -h 87 -w 87
icon_40pt.png -h 40 -w 40
icon_40pt@2x-1.png -h 80 -w 80
icon_40pt@2x.png -h 80 -w 80
icon_40pt@3x.png -h 120 -w 120
icon_60pt@2x.png -h 120 -w 120
icon_60pt@3x.png -h 180 -w 180
icon_76pt.png -h 76 -w 76
icon_76pt@2x.png -h 152 -w 152
icon_83.5@2x.png -h 167 -w 167
Icon.png -h 1024 -w 1024
icon_20pt.png -h 20 -w 20
icon_20pt@2x-1.png -h 40 -w 40
icon_20pt@2x.png -h 40 -w 40
icon_20pt@3x.png -h 60 -w 60
icon_29pt.png -h 29 -w 29
icon_29pt@2x-1.png -h 58 -w 58
icon_29pt@2x.png -h 58 -w 58
icon_29pt@3x.png -h 87 -w 87
icon_40pt.png -h 40 -w 40
icon_40pt@2x-1.png -h 80 -w 80
icon_40pt@2x.png -h 80 -w 80
icon_40pt@3x.png -h 120 -w 120
icon_60pt@2x.png -h 120 -w 120
icon_60pt@3x.png -h 180 -w 180
icon_76pt.png -h 76 -w 76
icon_76pt@2x.png -h 152 -w 152
icon_83.5@2x.png -h 167 -w 167
EOF
}

a="$1"
shift

if [ "${a}" == "icons" ]; then
    ios::generate-icons $@
elif [ "$a" == "create-icon" ]; then
    ios::create-icon
else
    echo "icons: generate icons from icon.svg"
fi
