#!/usr/bin/env bash

scriptdir=$(cd $(dirname $([ -L $0 ] && readlink $0 || echo $0)) && pwd)

function build_xcode() {
# I like to edit files in vim, but use xcode's debugger
    open *.xc*
    osascript <<EOD
    tell application "Xcode"
        activate
        tell application "System Events"
            perform (keystroke "r" using command down)
        end tell
    end tell
    tell application "Terminal"
        activate
    end tell
EOD
}

clang() {
    "$scriptdir/clang_complete.py" $@
}

a=$1
shift
if [ "$a" == "build" ]; then
    build_xcode $@
elif [ "$a" == "clang" ]; then
     clang $@
else
    echo "build: build the current project in and open xcode"
    echo "clang: create clang_complete file for xcode project"
fi
