#!/usr/bin/env bash

function build_heroku() {
    source venv/bin/activate
    heroku config:pull
    source .env
    export DATABASE_URL=$DATABASE_URL
}


if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    echo "start heroku project (with python virtualenv)"
    echo "pull database connection and environment"
else
    build_heroku $@
fi
