#!/usr/bin/env python2.7

def confirm(prompt):
    while True:
        try:
            i = raw_input(prompt+" ")
        except KeyboardInterrupt:
            return False
        if i.lower() in ('yes','y', ''): return True
        elif i.lower() in ('no','n'): return False

def prompt(prompt):
    try:
        return raw_input(prompt+" ")
    except KeyboardInterrupt:
        return ""

from todo_list import TodoList
def Run(args):
    if args.verb == 'count':
        tl = TodoList(lines())
        print tl.count()
    elif args.verb == 'tags':
        tl = TodoList(lines())
        print tl.tags()
    elif args.verb == 'table':
        tl = TodoList(lines())
        print tl.table()
    else:
        tl = TodoList(lines())
        print tl.string()
    return True



from os import path
from os import environ
from glob import glob
def lines(files=None):
    if files is None:
        files = environ.get('LISTS').split(':')

    for p in files:
        for l in glob(path.expanduser(p)):
            with open(l) as f:
                def yielder():
                    for line in f.readlines():
                        yield line
                yield l, yielder


import argparse, sys
def parseArgs():
    parser = argparse.ArgumentParser("todo")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("-a", dest="all", action="store_true")
    parser.add_argument("verb", choices=["list", "count", 'tags', 'table', 'quickfix'])

    args = parser.parse_args()
    return args


if __name__ == "__main__":
    if len(sys.argv) == 1: exit()
    try:
        args = parseArgs()
        if not Run(args):
                print "Error"
    except KeyboardInterrupt:
        pass
