#!/usr/bin/env python2.7

def confirm(prompt):
    while True:
        try:
            i = raw_input(prompt+" ")
        except KeyboardInterrupt:
            return False
        if i.lower() in ('yes','y', ''): return True
        elif i.lower() in ('no','n'): return False

def prompt(prompt):
    try:
        return raw_input(prompt+" ")
    except KeyboardInterrupt:
        return ""

from todo_list import TodoList
def Run(args):
    tl = TodoList(lines())
    if args.verb == 'count':
        print tl.count()
    else:
        print tl.string()
    return True



from os import path
from os import environ
def lines():
    for l in environ.get('LISTS').split(':'):
        with open(l) as f:
            for line in f.readlines():
                yield line


import argparse, sys
def parseArgs():
    parser = argparse.ArgumentParser("todo")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("-a", dest="all", action="store_true")
    parser.add_argument("verb", choices=["list", "count"])

    args = parser.parse_args()
    return args


if __name__ == "__main__":
    if len(sys.argv) == 1: exit()
    try:
        args = parseArgs()
        if not Run(args):
                print "Error"
    except KeyboardInterrupt:
        pass
