#!/usr/bin/env bash

scriptdir=$(cd $(dirname $([ -L $0 ] && readlink $0 || echo $0)) && pwd)


if [ "$MAILDIR" == "" ]; then MAILDIR=~/.mail; fi

mail::unread_mail() {
   local TIME=$1
   [ "$TIME" ] || TIME=1;
   local d
   if build system is-mac; then
       d=$(date -v-"$TIME"M +%Y%m%d%H%M)
    else
       d=$(date --date="$TIME minutes ago" +%Y%m%d%H%M)
   fi
    for m in $MAILDIR/*; do
        local p
        p=$(echo "$m" | sed 's:^'${MAILDIR}'::')
        n=$(echo "$p" | sed 's:^/::')
        username=$(cat ~/.local-dot/accounts/account.$n.username)
        mu find --fields='f: s' "m:${p}/INBOX" "date:$d..now" "t:${username}" OR "m:${p}/INBOX" "date:$d..now" "c:${username}" 2>/dev/null | sed 's/ <.*>:/:/'
    done
}

mail::unread_count() {
    n=0
    for m in $MAILDIR/*; do
        p=$(echo "$m" | sed 's:^'${MAILDIR}'::')
        n=$(echo "$p" | sed 's:^/::')
        username=$(cat ~/.local-dot/accounts/account.$n.username)
        num=$(mu find "m:${p}/INBOX" flag:unread "t:${username}" OR "m:${p}/INBOX" flag:unread "c:${username}" 2>/dev/null | grep -c '')
        [ "$num" ] || num=0
        n=$(($n + $num))
    done
    echo $n
}

mail::flag_count() {
    n=0
    for m in $MAILDIR/*; do
        p=$(echo "$m" | sed 's:^'${MAILDIR}'::')
        num=$(mu find "m:${p}/INBOX" flag:flagged 2>/dev/null | grep -c '')
        [ "$num" ] || num=0
        n=$(($n + $num))
    done
    echo $n
}

mail::read_count() {
    n=0
    for m in $MAILDIR/*; do
        p=$(echo "$m" | sed 's:^'${MAILDIR}'::')
        num=$(mu find "m:${p}/INBOX" flag:seen 2>/dev/null | grep -c '')
        [ "$num" ] || num=0
        n=$(($n + $num))
    done
    echo $n
}

mail::mail_attachment() {
    if build system is-mac; then
        "$scriptdir/view_attachment" $@
    else
        xdg-open "$1"
    fi
}

mail::mail_with_subject() {
   local SEARCH="$@"
   find $MAILDIR  -path '*/INBOX/*/*' -print0 | xargs -0 grep -H "$SEARCH"

}

mail::mail_link() {
    rm -f ~/.mailcap
    ln -s $scriptdir/mailcap ~/.mailcap
}

mail::gmail-auth() {
    $scriptdir/oauth2.py "$@"
}

mail::send-auth() {
    $scriptdir/send.py "$@"
}

arg=$1
shift
if [ "$arg" == "count" ]; then
    mail::mail_count $@
elif [ "$arg" == "unread" ]; then
    mail::unread_mail $@
elif [ "$arg" == "unread-count" ]; then
    mail::unread_count $@
elif [ "$arg" == "read-count" ]; then
    mail::read_count $@
elif [ "$arg" == "flag-count" ]; then
    mail::flag_count $@
elif [ "$arg" == "open-attachment" ]; then
    mail::mail_attachment "$@"
elif [ "$arg" == "link-mailcap" ]; then
    mail::mail_link $@
elif [ "$arg" == "with-subject" ]; then
    mail::mail_with_subject "$@"
elif [ "$arg" == "gmail-auth" ]; then
    mail::gmail-auth "$@"
elif [ "$arg" == "send-auth" ]; then
    mail::send-auth "$@"
else
    echo "count: count of mail in \$MAILDIR or ~/.mail maildir INBOX directories"
    echo "unread: print FROM:SUBJECT for new messages (same as count)"
    echo "open-attachment: decode type and open appropriately"
    echo "with-subject: grep all mails subject lines"
    echo "link-mailcap: link the mailcap file to ~/.mailcap"
    echo "gmail-auth: run the gmail oauth setup script"
    echo "send-auth: send email using send.py for oauth"
fi
