#!/usr/bin/env bash

scriptdir=$(cd $(dirname $([ -L $0 ] && readlink $0 || echo $0)) && pwd)


if [ "$MAILDIR" == "" ]; then MAILDIR=~/.mail; fi
if [ "$MAIL" == "" ]; then MAIL="$MAILDIR"; fi

mail_count() {
    s='new/'
    if [ "$1" == "-cur" ]; then s='cur/'; fi
    find $MAIL -path '*/INBOX/'"$s"'*' | wc -l | sed -e 's/^[ \t]*//g'
}

unread_mail() {
   TIME=1
   if [ "$1" != "" ]; then TIME=$1; shift; fi
   find $MAIL -mmin -$TIME -path '*/INBOX/new/*' | xargs sort -r | awk '/^From|^Subject/ { print }' | awk '!(NR%2){print$0p}{p=$0}' | sed -e 's/Subject//g' | sed -e 's/From: //g' | sed -e 's/\<[^][]*\>//g' | sed -e 's/ : /: /g'
}

mail_attachment() {
    "$scriptdir/view_attachment" $@
}

mail_with_subject() {
   # USES mu COMMAND
   SEARCH="$@"
   #mu find --fields 'l' s:${SEARCH} | grep 'INBOX'| xargs cat | awk '/^Subject/ { print }' | sed 's/Subject: //' | sed 's/'"${SEARCH}"': //'
   #mu find -f 's        l' s:"${SEARCH}" | grep 'INBOX' | awk -F '      ' '{print $1}' | sed 's/^'"${SEARCH}"'[ ]*//' 
   find $MAIL  -path '*/INBOX/*/*' -print0 | xargs -0 grep -H "$SEARCH" # xargs cat | awk '/^Subject: '"${SEARCH}"'/ { print }' | sed 's/Subject: //' | sed 's/'"${SEARCH}"': //'

}

mail_link() {
    rm -f ~/.mailcap
    ln -s $scriptdir/mailcap ~/.mailcap
}

gmail-auth() {
    $scriptdir/oauth2.py "$@"
}

send-auth() {
    $scriptdir/send.py "$@"
}

arg=$1
shift
if [ "$arg" == "count" ]; then
    mail_count $@
elif [ "$arg" == "unread" ]; then
    unread_mail $@
elif [ "$arg" == "open-attachment" ]; then
    mail_attachment "$@"
elif [ "$arg" == "link-mailcap" ]; then
    mail_link $@
elif [ "$arg" == "with-subject" ]; then
    mail_with_subject "$@"
elif [ "$arg" == "gmail-auth" ]; then
    gmail-auth "$@"
elif [ "$arg" == "send-auth" ]; then
    send-auth "$@"
else
    echo "count: count of mail in \$MAIL or ~/mail maildir INBOX directories"
    echo "unread: print FROM:SUBJECT for new messages (same as count)"
    echo "open-attachment: decode type and open appropriately"
    echo "link-mailcap: link the mailcap file to ~/.mailcap"
    echo "gmail-auth: run the gmail oauth setup script"
    echo "send-auth: send email using send.py for oauth"
fi
