#!/usr/bin/env bash

function license() {
    license="$1"
    if [ "$license" == "" ]; then license="mit"; fi
    builddir=$(cd $(dirname $([ -L $0 ] && readlink $0 || echo $0)) && pwd)
    license_dir="$builddir/licenses"
    license_file="$license_dir/$license"
    if [ -f "$license_file" ]; then
        year=$(date +%Y)
        name="$(git config user.name)"
        if [ "$name" ]; then
            namevar="--name"
        fi
        build template fill ${namevar} "${name}" --year ${year} "$license_file" > LICENSE
    else
        echo "Licenses (default MIT):"
        ls -1 "$license_dir"
    fi
}

ar() {
    echo $1
    echo $2
    echo $3
    echo $4
    echo $5
}

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    echo "create a license (default MIT)"
    echo "call with --list to see options"
else
    license $@
fi
