#!/usr/bin/env bash

id_from_name() {
    name="$*"
    echo ' # Crontab Installed With Build: '"${name}"
}

install_cron() {
    name="$1"
    if [ "${name}" == "" ]; then exit; fi
    uninstall_cron "${name}"
    id="$(id_from_name "${name}")"
    now="$(crontab -l 2>/dev/null)"
    sep="
"
    tab="$(sed -e "s|$|${id}|" "${name}")"
    c="${now}${sep}${tab}"
    echo "${c}" | crontab -
}

uninstall_cron() {
    name="$1"
    if [ "${name}" == "" ]; then exit; fi
    id="$(id_from_name "${name}")"
    crontab -l 2>/dev/null | grep -v "${id}" | crontab - > /dev/null 2>&1
}

edit_file() {
    name="$1"
    if [ ! -f "${name}" ]; then
        echo "${name} does not exist"
        return
    fi
    # shellcheck disable=SC2154
    "${EDITOR}" "${name}"
    install_cron "${name}"
}

edit_cron() {
    name="$1"
    if [ "${name}" == "" ]; then
        while IFS= read -r file <&3; do
            read -p "edit ${file} [y/N]" should
            if [[ "${should}" =~ [Yy].* ]]; then
                edit_file "${file}"
            fi
        done 3< <(echo ~/.cron; ls ~/.local-dot/conf/*.cron 2>/dev/null)
    else
        edit_file "${name}"
    fi

    if [ -z "$(crontab -l 2>/dev/null | grep 'SHELL=/bin/bash')" ]; then
        c="SHELL=/bin/bash
"
        echo "${c}$(crontab -l 2>/dev/null)" | crontab -
    fi
}



a="$1"
shift
if [ "${a}" == "install" ]; then
    install_cron "$@"
elif [ "${a}" == "uninstall" ]; then
    uninstall_cron "$@"
elif [ "${a}" == "edit" ]; then
    edit_cron "$@"
else
    echo "install file: installs file into the crontab (or updates)"
    echo "uninstall file: uninstalls the file"
    echo "edit [file]: edit and install the file (default is ~/.cron)"
fi
