#!/usr/bin/env bash

pandoctor::config() {
  DIR=$(pwd)
  while [ ! -f "$DIR/pandoctor.yaml" ] && [ "$DIR" != "/" ]; do
      DIR=$(dirname "$DIR")
  done
  [ -f "$DIR/pandoctor.yaml" ] && echo "$DIR/pandoctor.yaml" || return 1
}

pandoctor::get_option() {
cat "$1" | sed -n "s/$2"': \(.*\)/\1/p'
}

pandoctor::get_pandoctor_option() {
cat "$1" | sed -n 's/^# pandoctor '"$2"': \(.*\)$/\1/p'
}

pandoctor::get() {
  O=$(pandoctor::get_pandoctor_option "$1" "$2")
  [ "$O" == "" ] && O=$(pandoctor::get_option "$1" "$3")
  echo "$O"
}

pandoctor::run() {
    CONFIG=$(pandoctor::config) || (echo "no pandoctor.yaml found" >&2; exit 9)
    [ -f "$1" ] || (echo "not found: $1" >&2; exit 1)
    INPUT="$1"
    OUTPUT_BASE=${INPUT%.*}
    EXT=$(pandoctor::get "$CONFIG" ext to)
    OUTPUT="$OUTPUT_BASE.$EXT"
    [ "$EXT" == "" ] && OUTPUT="-"
    pandoc --defaults "$CONFIG" --output "$OUTPUT" "$INPUT"

}

pandoctor::run "$@"
