#!/usr/bin/env bash

search_md() { mdfind -onlyin . $@ | sort | sed "s:$(pwd)/::g"; }
search_find() { find . -name "*$@*" | sort | sed "s:\./::g"; }
search_contents() { grep -inIEr --color=ALWAYS "$@" . ; }
search_grep() { grep -lr "$@" . | sort | sed "s:\./::g"; }

search() {
    RESULTS=$("$@")
    echo "$RESULTS"
}

arg=$1
shift
if [ "$arg" == "content" ]; then
    search search_contents $@
elif [ "$arg" == "file" ]; then
    search search_grep $@
elif [ "$arg" == "file-find" ]; then
    search search_find $@
elif [ "$arg" == "file-grep" ]; then
    search search_grep $@
elif [ "$arg" == "file-mdfind" ]; then
    search search_md $@
else
    echo "content <search>: show highlighted content matches"
    echo "file <search>: just the files"
    echo "file-find <search>: just the files (using find)"
    echo "file-grep <search>: just the files (using grep)"
    echo "file-mdfind <search>: just the files (using mdfind)"
fi
