#!/usr/bin/env bash

ssh-share() {
    REMOTE="$1"
    PUB="$2"
    if [ "${REMOTE}" == "" ]; then echo "Specify a remote"; exit; fi
    if [ "${PUB}" == "" ]; then
        echo "Available Keys:"
        ls -1 ~/.ssh/*.pub
        echo
        read -p "Public Key (default ~/.ssh/id_rsa): " pub
        if [ "${pub}" == "" ]; then pub=~/.ssh/id_rsa; fi
        PUB="${pub}"
        eval PUB=${PUB}
    fi
    if [ ! -f "${PUB}" ]; then echo "${PUB} not a valid public key"; exit; fi

    cat "${PUB}".pub | ssh "${REMOTE}" 'cat - > .tempKey; mkdir -p ~/.ssh; cat .tempKey >> ~/.ssh/authorized_keys; rm .tempKey';
}

ssh-share "$@"
