#!/usr/bin/env bash

vagrant-ssh() {
    vagrant up; vagrant ssh; vagrant halt
}

a=$1
shift
if [ "$a" == "sup" ]; then
    vagrant-ssh $@
else
    echo "sup: up; ssh; halt (auto up, and halt after ssh is over)"
fi
