#!/usr/bin/env bash

scriptdir=$(cd $(dirname $([ -L $0 ] && readlink $0 || echo $0)) && pwd)

mac::ssh() {
    if [ "$1" != "" ]; then
        sudo systemsetup -setremotelogin off
    else
        sudo systemsetup -setremotelogin on
        ifconfig | grep broadcast
    fi
}

mac::dud() {
    open $scriptdir/dud.app

    link="$@"
    if [ "$link" == "mail" ]; then
        duti -s com.taylorlmoney.dud mailto
    elif [ "$link" == "photo" ]; then
        duti -s com.taylorlmoney.dud photos
    else
        echo "no linking found, you might need to edit dud's Info.plist"
        echo "options: mail, photo"
    fi
}

arg=$1
shift
if [ "$arg" == "ssh" ]; then
    mac::ssh $@
elif [ "$arg" == "dud" ]; then
    mac::dud $@
else
    echo "ssh [off]: no args enables remote login, false or no diables"
    echo "dud [type]: assigned the link type to dud (eg mail)"
fi
