#!/usr/bin/env bash

scriptdir=$(cd $(dirname $([ -L "$0" ] && readlink "$0" || echo "$0")) && pwd)

fill_template() {
    "${scriptdir}/fill_template" "$@"
}

example_template() {
    cat "${scriptdir}/example.template"
}


arg=$1
shift
if [ "${arg}" == "fill" ]; then
    fill_template "$@"
elif [ "${arg}" == "example" ]; then
    example_template $@
else
    echo "fill [-v] [--outfile file] <file>: read file, and fill out as template"
    echo "if -v then echo the templates as command line arguments first"
fi
