#!/usr/bin/env bash

function ctagger {
    LC_COLLATE=C
    /usr/local/bin/ctags -f .tags --sort=yes --exclude=.git --exclude='*.log' -R . >/dev/null 2>/dev/null
}

function code_tags() {
    LC_COLLATE=C
    # parents directories where code is, go through them all
    # and place .tags in all folders with .git
    current_dir="`pwd`"
    for f in $@
    do
        cd "$current_dir"
        cd "$f"
        find . -name ".git" -print0 | while IFS= read -r -d $'\0' line; do
            cd "$current_dir"
            cd "$f"

            if [ -d "$line" ]
            then
                cd "$line"
                cd ..
                ctagger
            fi
        done
    done
}

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    echo "generate ctags for current directory"
    echo "if arguments present then recursively"
    echo "search through directories and find tags"
    echo "for each git repo"
    echo "(ctags must be install in /usr/local/bin)"
elif [ "$1" == "e" ]; then
    etags -f .tags--fields=+l *.java
elif [ "$1" == "" ]; then
    ctagger
else
    code_tags $@
fi
